[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_FLAGS = "--prefer-offline --no-audit"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/demo"
  to = "/.netlify/functions/demo"
  status = 200

[[redirects]]
  from = "/api/spotify/playlist/*"
  to = "/.netlify/functions/spotify-playlist"
  status = 200

[[redirects]]
  from = "/api/debug/env"
  to = "/.netlify/functions/debug-env"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
