[build]
  publish = "dist/spa"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/demo"
  to = "/.netlify/functions/demo"
  status = 200

[[redirects]]
  from = "/api/spotify/playlist/*"
  to = "/.netlify/functions/spotify-playlist"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
